[package]
name = "gd-spout"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext.git", version = "0.3.4" }
spout-sys = { path = "../spout-sys" }