[package]
name = "spout-sys"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0.148"

[dependencies]
cxx = "1.0.148"
windows = { version = "0.60.0", features = ["Win32_Graphics_Direct3D12", "Win32_Graphics_Dxgi_Common"] }


